### ISSUE TITLE
Add tree endpoint to fetch ancestors of a catalogue item

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#103]
# Request

Given a catalogue item (or model) `domainType` and `id`, provide an endpoint for the tree that returns the ancestors of that item, instead of its children.

# Rationale

There is a UI feature request in MauroDataMapper/mdm-ui#219 which asks for the item currently on display and the catalogue tree to be in sync - i.e. clicking a link from a Data Model to a Data Class would display the Data Class details in view _and_ automatically select that Data Class in the tree.

This is not currently possible in the UI because the view transitions are only aware of the lowest catalogue item in the tree selected - the current item. At this point, it may be that the tree view has not fully expanded yet, so there is no obvious way of locating it in the (virtual) tree.

Having a list of ancestors available would allow the UI to start from the top of the tree and work its way down until the current item is found.

**Comment by olliefreeman** [comment]
@pjmonks the endpoint is `api/tree/${containerDomainType}/${catalogueItemDomainType}/${catalogueItemId}/ancestors`

e.g. 
* `/api/tree/folders/dataClasses/$dataClassId/ancestors`
* `/api/tree/folders/dataModels/$dataModelId/ancestors`
