### ISSUE TITLE
Email update does not work

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-core#105]
Steps:
1. Update email from which registration details are sent in the Admin Console (email.from.address). 
2. Restart docker

Expected result
Admin console > email.from.address is showing the updated email address, and all notifications are sent from the new email address

Actual result:
Admin console > email.from.address is showing the old email address (the one provided during the composing of an image)

**Comment by olliefreeman** [comment]
can i just ask what command you're using to restart docker? i just want to make sure i replicate this exactly

**Comment by jelenadreskai** [comment]
I use the stop and start button in docker.

**Comment by olliefreeman** [comment]
the changes are being replicated to the database which suggests to me that the method being used for starting and stopping docker is actually removing the postgres volume and therefore removing all data from the database.
Please use docker-compose to start and stop containers as this will not remove volumes without the additional argument
