### ISSUE TITLE
"Validation Error(s) occurred during save():" >> scraping in models using postman

### ISSUE THREAD

**Issue by theresanoble** [MauroDataMapper/mdm-core#110]
**Describe the bug**
Unable to scrap in SQL models, getting the follow error:

{"status":422,"reason":"Unprocessable Entity","errorCode":"UEX--","message":"Validation Error(s) occurred during save():","path":"/api/dataModels/import/uk.ac.ox.softeng.maurodatamapper.plugins.database.sqlserver/SqlServerDatabaseDataModelImporterProviderService/5.0.0","devMode":false,"version":"4.7.0","validationErrors":{"total":1,"errors":[{"message":"Property [label] of class [class uk.ac.ox.softeng.maurodatamapper.datamodel.DataModel] with value [BONE_MARROW_ASPIRATES_std] must be unique by branch name"}]}}

Bone_Marrow_Aspirates is a finalised model within the OUH instance, I was attempting to scrape in a new version.

**To Reproduce**
1. Go to https://oxnetdwa02.oxnet.nhs.uk/mauro-data-mapper/
2. Using postman or UI attempt to scrape in Bloodtrack or Bone_Marrow_Aspirates (same error occurred) (see screenshot attached for setting used)

**Expected behavior**
I would expect it to work as it did for Badgernet, where in it created V2 of model.

**Screenshots**
![Screenshot 2021-07-22 at 13 44 38](https://user-images.githubusercontent.com/67739552/126641559-827c52b6-c52b-48db-afbb-465237c667f3.png)

**Desktop (please complete the following information):**
 - OS: Mac 11.4
 - Browser Safari
 - Version 14.1.1

**Comment by olliefreeman** [comment]
fixed inside MauroDataMapper-Plugins/mdm-plugin-database@fdf106f0897de87ead6fb9110ef88d63e0e36b0e
