### ISSUE TITLE
Changes to aliases are not being picked up as differences in merge diff

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#112]
**Describe the bug**
If adding or changing an `alias` or `classifier` on a catalogue item, then try to merge that item into another branch, the `mergeDiff` endpoint does not pick this up as a change.

**To Reproduce**
See screenshots below.

**Expected behavior**
A change should appear in the `mergeDiff` response to list what has changed in the alias and/or classification fields.

**Screenshots**
Taken from the UI using a Data Class. The _source_ Data Class_ looks like this:

![image](https://user-images.githubusercontent.com/3219480/126775031-ff7a8c5f-37b3-43a5-8d3f-09396355a343.png)

The _target_ Data Class looks like this:

![image](https://user-images.githubusercontent.com/3219480/126775062-033ed492-aba0-4f3d-8178-eca47813320a.png)

But if you try to merge _source_ into _target_ the alias and classifier don't appear in the changes list:

![image](https://user-images.githubusercontent.com/3219480/126775150-f1364413-caae-49af-a38d-e85a34e6a723.png)

**Comment by olliefreeman** [comment]
classifiers arent and never have been included in teh list of diffs, and its complicated to do so, so we shouldnt include them, however aliases should be...i'll work out whats happening

**Comment by olliefreeman** [comment]
aliases were never added...they must have been missed

**Comment by olliefreeman** [comment]
opened #119 to handle classifiers as an enhancment
