### ISSUE TITLE
Cannot determine if a model can use the merge endpoints or not

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#121]
**Describe the bug**
When testing the merge behaviours between Data Models and Versioned Folders, I have noticed it that the UI still allows the "Merge" option for a Data Model that sits under a Versioned Folder. I believe that this action should not be present, since the merge will be handled by the ancestor Versioned Folder instead.

**To Reproduce**
Steps to reproduce the behavior in the UI:
1. Create a Versioned Folder.
2. Add a Data Model under the Versioned Folder.
3. Finalise the Versioned Folder to create version 1.0.0
4. Create the next version of the Versioned Folder. Choose to create a new branch, producing a `main` and another branch to work from.
5. Select the second branch of the Versioned Folder and view the Data Model within it, select that.
6. Click on the triple-dot menu

**Expected behavior**
Returning the model should include an `allowedAction` that states whether merging is allowed or not.

**Screenshots**

![image](https://user-images.githubusercontent.com/3219480/127483326-29fa552f-97f7-4e34-893c-d3283cdfe600.png)

**Additional context**
Looking at the core codebase, there seems to be a `MERGE_INTO_ACTION` constant, but it does not get included in any `allowedActions` collections for models. This would seem to be the most relevant for this situation, then the UI can determine if the "Merge" option should be included or not.

**Comment by olliefreeman** [comment]
yes that action was intended for the merging...and yes its not being removed

**Comment by pjmonks** [comment]
@olliefreeman Looking at the commit history of this issue, I'd have thought I would see `mergeInto` appear in a VF `availableActions` list but I still don't:

![image](https://user-images.githubusercontent.com/3219480/130794549-3febb9c1-acce-4163-bf9c-a87bdf2ebba1.png)

According to the rules in ad3e6db, this is not finalised or a main branch, so I would have though the `mergeInto` action would appear here for the UI to determine the options to show. Have I missed something?
