### ISSUE TITLE
Incorrect merge diff found with inner Data Classes inside Versioned Folder

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#122]
**Describe the bug**
Assume that a Versioned Folder branch contains:

1. A Data Model
2. That then contains a Data Class
3. That Data Class then gets another Data Class added as a child

If merging point 3 into the main branch, the diff returned is a _deletion_ instead of an _addition_. Why is this?

**To Reproduce**
1. Create a Versioned Folder, then inside a Data Model, then inside a Data Class.
2. Finalise the Versioned Folder to 1.0.0
3. Branch off version 1.0.0 to create a main and another branch - "test-branch"
4. In "test-branch", add another Data Class inside the existing Data Class (to produce a parent-child relationship). The structure should then look like the screenshot below.
5. Go to merge the Versioned Folder from "test-branch" to "main"

**Expected behavior**

Because the child Data Class is new and does not exist in the main branch yet, I would have assumed the diff would say it is being "added", not "deleted".

**Screenshots**
Note the structure below. A child Data Class was added to the test branch, where is does not exist in the main branch:

![image](https://user-images.githubusercontent.com/3219480/127493712-1e713fa7-cb02-49d8-a8f4-cbe1fdb873d4.png)

This is the result of the merge diff on this structure:

![image](https://user-images.githubusercontent.com/3219480/127493822-313a232e-3da3-4e42-8aa9-0e3a461d79ed.png)

**Additional context**

If you commit this change to the main branch, nothing actually happens - the child Data Class still exists in the test branch, and the main branch still does not include it.

**Comment by pjmonks** [comment]
I've now found a similar issue related to Data Elements.

Here is my test branch of a VF. The highlighted DC contains a new DE called "First Data Element":

![image](https://user-images.githubusercontent.com/3219480/127495894-bb955de0-670f-4491-95ee-a270033d3b98.png)

To confirm, this does not exist in the main branch:

![image](https://user-images.githubusercontent.com/3219480/127495959-7cdd9195-6a7c-4088-bc7b-508bce5159ca.png)

But this is the merge diff returned:

![image](https://user-images.githubusercontent.com/3219480/127496021-2b36fdc4-390a-44f1-8293-9354c456a101.png)

**Comment by pjmonks** [comment]
And one final thing... Adding a DE to the child DC like this:

![image](https://user-images.githubusercontent.com/3219480/127496275-af369c27-0106-46a1-935e-0b791e1563e4.png)

The merge diff does not return this one at all:

![image](https://user-images.githubusercontent.com/3219480/127496346-94ee2ac9-7168-4826-93e2-bfa6087ccd61.png)

**Comment by olliefreeman** [comment]
odd...

**Comment by olliefreeman** [comment]
this is odd as the tests we have cover this exact scenario
```
{
      "path": "vf:Functional Test VersionedFolder 3$source|dm:Functional Test DataModel 1$source|dc:existingClass|dc:addLeftToExistingClass",
      "isMergeConflict": false,
      "isSourceModificationAndTargetDeletion": false,
      "type": "creation"
    },
```

**Comment by olliefreeman** [comment]
@pjmonks can you retest this please, I have locally run up your branch plus mdm-app-build and I'm getting the creation as id expect

` http://localhost:8080/api/versionedFolders/5a42c7e8-da87-462e-bc61-8c95e094409e/mergeDiff/7af7fe25-968a-4985-aa49-6cc68f606a8f?isLegacy=false`

```json
{
    "sourceId": "5a42c7e8-da87-462e-bc61-8c95e094409e",
    "targetId": "7af7fe25-968a-4985-aa49-6cc68f606a8f",
    "path": "vf:test$test",
    "label": "test",
    "count": 1,
    "diffs": [
        {
            "path": "vf:test$test|dm:pdf$test|dc:dfgdfgdf|dc:hghfgf",
            "isMergeConflict": false,
            "isSourceModificationAndTargetDeletion": false,
            "type": "creation"
        }
    ]
}
```

<img width="273" alt="Screenshot 2021-07-30 at 13 10 50" src="https://user-images.githubusercontent.com/2587424/127651019-77af36b2-fb59-421f-a4a0-0c6f208dce1f.png">


I think you had the url sending the ids in the wrong order when you tested this and got this error...thats the only explanation I can think of

**Comment by pjmonks** [comment]
Sorry @olliefreeman , but I must have the `sourceId` and `targetId` the right way round, otherwise the other diffs I see wouldn't be right either.

Look at this structure:

![image](https://user-images.githubusercontent.com/3219480/127658254-8b8c5a2c-d24b-4a2b-b1d1-9eb09997d802.png)

Everything I've highlighted in green would be _additions_ when I merge `testBranch` into `main`. But this is the diff I see:

![image](https://user-images.githubusercontent.com/3219480/127658454-a84e9c52-cc40-412e-9b1c-f6f52daea68a.png)

If I had the `source` and `target` IDs the wrong way round, then all of them would be wrong, but I'm finding that 3 are correct and 2 are wrong. I can't understand why.

Another example to prove that I can replicate it on my system:

![image](https://user-images.githubusercontent.com/3219480/127658822-49db5ce1-69f6-40d9-a785-ca070600275a.png)

![image](https://user-images.githubusercontent.com/3219480/127658967-0379e0f0-e367-44bc-8a53-88ef14a5c70c.png)

**Comment by olliefreeman** [comment]
this is really bizarre ... why does it work fine for me but not for you ....

**Comment by olliefreeman** [comment]
and we have in our tests ... we have an "existing class" DC which we add a DC to and the json comes back 
```json
{
      "path": "vf:Functional Test VersionedFolder 3$source|dm:Functional Test DataModel 1$source|dc:existingClass|dc:addLeftToExistingClass",
      "isMergeConflict": false,
      "isSourceModificationAndTargetDeletion": false,
      "type": "creation"
    },
```

**Comment by pjmonks** [comment]
@olliefreeman I have been retesting this issue with the scenarios I've described previously. My original issues don't seem to happen anymore, so it can now diff:

1. Data Model with Data Class and inner Data Class
2. Data Model, Data Class which contains Data Element

But I can still reproduce a bizarre situation around Data Elements added to child Data Classes. I'm not sure how edge-case this is though.

**Steps to reproduce**

From the UI:

1. Create a VF called "VF Data Models"
2. Then create a DM inside the VF called "DM Test"
3. Then create a DC inside the DM called "DC Test"
4. Finalise the VF to version 1.0.0
5. Create a new branch off of VF 1.0.0 called "test-branch"
6. Under "test-branch", create a child DC under "DC Test" called "DC Test Inner"
7. Create a DE and DT under "DC Test" called "DE Test" and "DT Test".
8. Merge-diff "test-branch" compared to "main" now and merge the changes made - these should be the new child DC, DE and DT. But **keep** the source branch!
9. Now, under "test-branch", create a DE under "DC Test Inner" using the same DT
10. Merge-diff again.

At this point I'm able to see this diff:

![image](https://user-images.githubusercontent.com/3219480/130830725-f287758e-9be9-4165-90a5-59b63733013e.png)

This is wrong - the DE added to the inner DC is an **addition**, not a **deletion**.

**Additional context**

I have tried to debug the diff operation happening, but cannot easily see the point where a deletion is listed in the diffs. Inspecting most of the variables shows that a new DE is seen as an addition, but maybe it is related to the common ancestor - I've seen that source and target are first compared against common ancestor, then somehow compared to each other (though I couldn't track that point in the code).

Also, unless this is relevant, the `MergeDiff.flatten()` method shows me the final diff tree between source and target, but I can expand the tree and see a `NullPointerException` happening down towards the point where the inner DE is. Is this relevant at all?

![image](https://user-images.githubusercontent.com/3219480/130831127-a94bca88-7e95-4d51-94dd-84e325dd1dcc.png)
