### ISSUE TITLE
Denied access to submit a DOI profile post-finalise

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#130]
**Describe the bug**
The DOI profile should be allowed to have values saved to a catalogue item after that item is finalised; this is to ensure that changes can be made before submitting the profile to the DOI system and the core can make modifications automatically.

However, I've found that if submitting the DOI profile to save it using the `POST /api/{domainType}/{id}/profile/{namespace}/{name}` endpoint (before requesting the DOI), then a `403` response is returned instead, not getting as far as contacting the DOI system.

**To Reproduce**
From the UI:
1. Select a Data Model. Make sure it is finalised and public to anonymous users.
2. Under the "Description" tab, click on the triple-dot menu that should be visible, then select "DOI Submission > Draft".
3. In the Edit Profile dialog, enter any values into the mandatory fields.
4. Click "Save"
5. Check the network tab in the browser to see the request sent.

**Expected behavior**
The DOI profile should have been saved to the catalogue item, and the core should then have continued to send the DOI profile to the DOI system to get an identifier.

**Screenshots**
![image](https://user-images.githubusercontent.com/3219480/128738607-bfa76daf-e467-4ebf-b3e0-cdc779775fad.png)

![image](https://user-images.githubusercontent.com/3219480/128738655-f9a26fab-991d-41cb-9d55-94c3be65a7d9.png)

**Additional context**
I'm wondering if this access denied error is because the model is finalised and data cannot be written back to the model now - is the `finalisedEditAction` value checked in this case?

The issue is with saving the profile, which suggests it's an `mdm-core` issue. However, if it is related to the [MauroDataMapper-Plugins / mdm-plugin-digital-object-identifiers](https://github.com/MauroDataMapper-Plugins/mdm-plugin-digital-object-identifiers), then please transfer this issue to that repo.

**Comment by olliefreeman** [comment]
We never added the ability to mark profiles as editable after finalisation….once we do that this will work

**Comment by olliefreeman** [comment]
this is fixed
