### ISSUE TITLE
The Last Updated and Created options on the Advanced Search menu on Mauro is not working properly 

### ISSUE THREAD

**Issue by Jayafo** [MauroDataMapper/mdm-core#162]
**Describe the bug**
When a user searches for a model using the **ADVANCED SEARCH** option on Last Updated and Created menu option, the functionality is not working as expected compared to other advanced search the Domain Types and Search Types. When the delete the icon is selected after entering some values the screen doesn’t refresh and sometimes display server error.  
**To Reproduce**
Steps to reproduce the behaviour:
1.	Go to 'Mauro'
2.	Select the Search menu 
3.	Type in a search function
4.	Select the Advanced option 
5.	Perform the following search option Last Updated and Created 
6.	Searches are returned 
7.	Select the delete function on these search options 
8.	Screen is not refreshing 
![after the delete of the details](https://user-images.githubusercontent.com/87768436/136406218-84c9b483-2ae9-4f9f-ba61-ea5dc73efa35.PNG)
![Before inserting values](https://user-images.githubusercontent.com/87768436/136406224-4cdfb1c4-ce5d-4f85-98bc-9f9d707a56bc.PNG)

**Expected behaviour**
Screen should refresh and display the full search previously  

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jayafo** [comment]
Hello @jamesrwelch i have retested this defect and clearing of this fields is not refreshing the page compare to other search functions. 

Failed Retest and can you please reopen the defect. 

Thanks.

**Comment by jamesrwelch** [comment]
@gammonpeter Are you able to look at this again, please - wrt Jayafo's comment above

**Comment by olliefreeman** [comment]
@jamesrwelch @Jayafo what do you mean by clearing of the search options resulting in refreshing??? Do you expect clearing an option to auto re-search and show the results????

the reason I ask is that those filters are not dynamically applied by the UI, you have to click the search button again after changing the search options to ask the backend for the results. 

And therefore is it failing because the cleared search options aren’t being applied when the search button is clicked or are you expecting behaviour which doesn’t exist??

**Comment by olliefreeman** [comment]
Also I would argue that the “retest” scenario is not the same as the original issue raised and therefore this should be a new bug

**Comment by Jayafo** [comment]
Hello @olliefreeman The issue is that once you select the dates for either the Last Updated field or created field, the screen refreshes and populate more specific result, then when these fields are deleted the screen is expected to refresh and display previously returned searched results before the last updated and created fields were used

**Comment by olliefreeman** [comment]
Okay so this is actually a ui issue not a core issue then

**Comment by olliefreeman** [comment]
reopened the linked UI issue

**Comment by Jayafo** [comment]
Failed Retest and tracking under 395
