### ISSUE TITLE
Importing Data Model as Finalised isn't finalising Data Classes

### ISSUE THREAD

**Issue by gammonpeter** [MauroDataMapper/mdm-core#177]
Upon importing a Data Model as finalised the, Data Classes within that data model arn't set as finalised

**Comment by olliefreeman** [comment]
1. need to confirm the breadcrumbs coming back to the UI first that it doesn't have the finalised information we expect
2. `uk.ac.ox.softeng.maurodatamapper.core.provider.importer.ModelImporterProviderService#checkImport` is called by all model importers
3. `uk.ac.ox.softeng.maurodatamapper.core.model.ModelService#checkFinaliseModel(K, java.lang.Boolean, java.lang.Boolean)` finalises the model

that final step should result in the the BreadcrumbTree for the DCs etc being stored with the DM as finalised, however this may not be happening for some reason

`uk.ac.ox.softeng.maurodatamapper.core.model.ModelService#finaliseModel` is the method called by finalising a model which is manually created...the vital step in this is `uk.ac.ox.softeng.maurodatamapper.core.facet.BreadcrumbTreeService#finalise` which acts on the db directly as its faster than actually getting hibernate to do it
