### ISSUE TITLE
Copy class fails with validation error

### ISSUE THREAD

**Issue by GBishop-PHSA** [MauroDataMapper/mdm-core#182]
**Describe the bug**
When copying a data class that has other properties on the Data Class and other properties on the Data Element, the newly created class fails to save with a validation error on the Data Element property.

The failure happens at: https://github.com/MauroDataMapper/mdm-core/blob/09bc29cc2bd703a1c304ff9b4ff8fb681e89a068/mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/facet/Metadata.groovy#L46

because ident() returns null.

**To Reproduce**
1. Create a new Data Model
2. Create a new Data Class for the data model
3. Go to Other Properties and add a property to the data class
4. Create a new Data Element for the data class
5. Go to Other Properties for the Data Element
6. Go to a different Data Model than the one created above
7. Create a new Data Class by using Copy Data Class(es) from
8. Select the original Data Modal and click Next Step
9. Select the Data Class created above and click Submit Data Class button
10. See error: - Field error in object 'uk.ac.ox.softeng.maurodatamapper.core.facet.Metadata' on field 'multiFacetAwareItemId': rejected value [null];

**Expected behavior**
The new copied data class should be created with Other Properties on the class and data element level created.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version mdm-core 4.10.0

**Additional context**
When debugging, the validation error occurs when saving the Data Element other property.

**Comment by GBishop-PHSA** [comment]
@olliefreeman  I wasn't able to determine why the Data Element property did not pass validation during a save from a class copy. The object has the namespace, key and value populated during validation, but still fails. If I remove the Other Property from the Data Class, but leave the Data Element property, the copy succeeds without an error.

**Comment by olliefreeman** [comment]
So the copy should be running the CaralogueItemService method to sort all the ids after inserting. A test should be created which copies a DC with DE content with facet content and then see why that method isn’t being called.

**Comment by GBishop-PHSA** [comment]
It calls uk.ac.ox.softeng.maurodatamapper.core.model.CatalogueItemService#save(java.util.Map, K). Which method sorts the ids? Is it the call to updateFacetsAfterInsertingMultiFacetAware?

**Comment by GBishop-PHSA** [comment]
Copy class functionality has no issues, but the last step in the DataClassController, is to call saveResource on the copied class. After the save is processed, the data element metadata is missing the multi_facet_aware_item_id in the table core.metadata.

The entry in datamodel.join_dataelement_to_facet is correct for the data element metadata, but any call to get data element metadata from the UI, requires the value in the core.metadata table.

**Comment by jelenadreskai** [comment]
@jamesrwelch or @olliefreeman Can you assign this issue to @GBishop-PHSA .

**Comment by GBishop-PHSA** [comment]
@olliefreeman I'm stuck on how to resolve this issue, so I've created a pull request with an incorrect solution for review. I updated the BootstrapDatamodel to add metadata on the class and element level, but also had issues getting the metadata to save correctly on the call to saveAndCheck().

**Comment by olliefreeman** [comment]
@GBishop-PHSA when you open a PR if you add `Fixes #xxx` to the description it auto links the PR to the Issue which makes resolution easier/automatic
