### ISSUE TITLE
Both error and success notifications are displayed during importation of Data Model in JSON format 

### ISSUE THREAD

**Issue by Jayafo** [MauroDataMapper/mdm-core#196]
**Describe the bug**
When a user import Data Model in JSON format both error and success notification are displayed at the bottom of the screen and the importation is successful. 
**To Reproduce**
Steps to reproduce the behaviour:
1.	Go to 'Mauro'
2.	Click on 'Import models> icon 
3.	Select <Import Data Models>
4.	Select JSON format and fill other options 
5.	Select the <Import Model(s)> CTA
6.	Both error and success notification are displayed 
**![error and success](https://user-images.githubusercontent.com/87768436/135468928-db1e88fd-ded5-4ea2-a908-4e30167e1fbf.PNG)**
The “Models imported successfully” option should display  

**Error Message** 

 "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 404,
  "statusText": "OK",
  "url": "https://rost6-mauro-james-2021-09.rost6.dev.dataproducts.nhs.uk/nhsd_mauro_test/api/dataModels/18133825-3881-49ab-939c-7f5572def615",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://rost6-mauro-james-2021-09.rost6.dev.dataproducts.nhs.uk/nhsd_mauro_test/api/dataModels/18133825-3881-49ab-939c-7f5572def615: 404 OK",
  "error": {
    "path": "/api/dataModels/18133825-3881-49ab-939c-7f5572def615",
    "resource": "DataModel",
    "id": "18133825-3881-49ab-939c-7f5572def615"
  }
}

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olliefreeman** [comment]
Linked to MC-9723

**Comment by olliefreeman** [comment]
okay so this is fixed as much as it can be from the API, its still possible the UI shows multiple messages but that will be down to how it calls the SC endpoints.

**Comment by olliefreeman** [comment]
this should be solved by MC-9735
