### ISSUE TITLE
Property DomainID cannot be null when copying an element 

### ISSUE THREAD

**Issue by oughnic** [MauroDataMapper/mdm-core#208]
**Describe the bug**
When copying a data element from one model to another, the error "Property [DomainID] cannot be null" is shown in the UI.

**To Reproduce**
1.  Create a model and class
2.  Add a data element, copying from an existing element

**Expected behavior**
The element should make a copy without error

**Screenshots**
![image](https://user-images.githubusercontent.com/27196895/144862374-992fc065-9f83-4ba1-b4f1-8615c7104087.png)

**Comment by olliefreeman** [comment]
domainId is a BreadcrumbTree field

i suspect the copied DE is being saved using the dataElementService but the DataType is being created as well and whilst its being saved the dataTypeService.save() method isnt being used and therefore the facets & BTs arent being updated. This is a guess.

**Comment by aaronforshaw** [comment]
I have not been able to reproduce the bug in exactly the way described by @oughnic, but the following scenarios provoked the same error:

1. Use the JSON Data Model importer to import a non-finalised Data Model with at least one Enumeration Type
2. Try to edit any properties of a Data Element which uses the Enumeration Type

OR

1. Use the JSON Data Model importer to import a non-finalised Data Model with two Data Classes, each using at least one Enumeration Type
2. Copy a Data Element (which uses an Enumeration Type) from one Data Class to the other

In both scenarios the failure to check the Breadcrumb Tree when importing the Data Model led to a null domainId. This causes the validation error on subsequent updates.

**Comment by PaulChapmanPM** [comment]
Hi @olliefreeman - I think the comments above mean that this has been fixed.  If so, would you confirm if the fix has been applied to https://modelcatalogue.cs.ox.ac.uk/nhsd-test (or when it will be if not).
Thanks.

**Comment by jamesrwelch** [comment]
@PaulChapmanPM If it's marked as fixed in GitHub, that means the fix is in the develop branch.  When it gets added to a release, this ticket will be updated again.  Once we have a new release, I'll update the systems we host and let you know.

**Comment by PaulChapmanPM** [comment]
Great.  Thanks James.
