### ISSUE TITLE
Incorrect search results by classifier

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-core#211]
Use and Advanced Search to find a date model that contains "data" in the name, and is classified as "Environment: PopData".

Expected results:
None should show up in the results, because none of the data models were classified using this classifier

Current result:
DataModel Classified shows up in the results, even though this classifier is not applied to that data model.

It has been confirmed that in the source code, that Classifier labels are searched after splitting the label by words (using WordDelimiterGraphFilterFactory from Lucene), whereas the expectation that we want the exact match. It did find the data model below, because it had "Environment" keyword in the list of classifiers.

![image](https://user-images.githubusercontent.com/81437684/145264826-ea319b0a-02bd-48d3-905a-c3c902835e04.png)

![image](https://user-images.githubusercontent.com/81437684/145264857-12a0599f-2a5b-4766-a4c1-5ddd09700160.png)

**Environment**
MDM 4.10/6.6.0

**Comment by jelenadreskai** [comment]
@jamesrwelch @olliefreeman 
We made a code change to do the exact match when someone is picking classifiers to perform a search by classifier. If you agree with the solution, please assign this bug to @GBishop-PHSA, and she can contribute the code change.

**Comment by jamesrwelch** [comment]
Brilliant, thanks!
