### ISSUE TITLE
500 NullPointerException when requesting model tree

### ISSUE THREAD

**Issue by Sunspark** [MauroDataMapper/mdm-core#214]
**Describe the bug**
An authenticated user that has been granted permission to view an object cannot retrieve the model tree. This appears to be an internal server error.

**To Reproduce**
Given a mauro instance containing models
![image](https://user-images.githubusercontent.com/5920776/145419914-f3b969b9-5549-4bd2-aa5c-83d8aa68efa1.png)
Given a user group
![image](https://user-images.githubusercontent.com/5920776/145420204-b1c884e9-0772-4912-b355-df9d20484d90.png)
Given a user, assigned to previous group
![image](https://user-images.githubusercontent.com/5920776/145420433-72a4b18c-7014-4982-a660-6f9829aa1352.png)
Given the group is assigned Reader permission to a model (also errors on 'editor')
![image](https://user-images.githubusercontent.com/5920776/145422577-39d1051d-217b-4d9e-81c2-31402421e304.png)
When the user authenticates to the mauro instance
And attempts to browse the model tree
Then an error is produced
![image](https://user-images.githubusercontent.com/5920776/145423005-6fd37605-834c-47fb-b2fb-0e43ba282696.png)

**Expected behavior**
Then a model tree displaying the user's available models should be shown

**Desktop (please complete the following information):**
 - OS: Win10, Azure VM. Running Mauro in Docker for Windows.
 - Browser: Chrome, Postman
 - Version:
    mauro-data-mapper:
        image: "maurodatamapper/mauro-data-mapper:${MDM_TAG}"
        build:
            context: mauro-data-mapper
            args:
                MDM_APPLICATION_COMMIT: 4.11.0
                MDM_UI_COMMIT: 6.7.0
                ADDITIONAL_PLUGINS: "uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database-sqlserver:5.1.0;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-csv:3.0.0;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-database-postgresql:4.0.0;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-excel:4.0.1"
                MDM_UI_THEME_NAME: "default"

**Additional**
When the user is given no permission
![image](https://user-images.githubusercontent.com/5920776/145421553-e1d1b2d0-9383-4122-83ce-7caa4fa015a2.png)
The model tree returns OK
![image](https://user-images.githubusercontent.com/5920776/145421763-55ed0f7c-590e-4317-bb9a-bb73a99c1878.png)

**Additional**
When the object is exposed via 'all authenticated users'
![image](https://user-images.githubusercontent.com/5920776/145422093-afe0e6b1-1cf7-437a-9e4b-096739fa6a7c.png)
The model tree returns OK
![image](https://user-images.githubusercontent.com/5920776/145422248-6a8c2d0e-c77c-45d5-bec1-4e89452b92c8.png)

**Additional**
The error appears to be in the JSON file that is returned by the server, and the same error can be created by going through the API via postman. The JSON returned is:
```
{
    "status": 500,
    "reason": "Internal Server Error",
    "errorCode": "UEX--",
    "message": "JS-- - Unknown error",
    "path": "/api/tree/folders",
    "devMode": false,
    "version": "4.11.0",
    "exception": {
        "type": "NullPointerException",
        "stacktrace": [
            "uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemService$_wrapModelTreeItemsInContainerTreeItems_closure40.doCall(TreeItemService.groovy:608)",
            "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemService.wrapModelTreeItemsInContainerTreeItems(TreeItemService.groovy:606)",
            "uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemService.buildContainerTreeForModelTreeItems(TreeItemService.groovy:596)",
            "uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemService.$tt__buildContainerTree(TreeItemService.groovy:161)",
            "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)",
            "org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)",
            "grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)",
            "uk.ac.ox.softeng.maurodatamapper.core.tree.TreeItemController.index(TreeItemController.groovy:96)",
            "java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_L(VirtualHandle.java:130)",
            "java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)",
            "org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)",
            "org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)",
            "org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)",
            "org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)",
            "org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)",
            "org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
            "org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)",
            "org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
            "org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)",
            "org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)",
            "org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)",
            "org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)",
            "org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)",
            "org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)",
            "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)",
            "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)",
            "java.lang.Thread.run(Thread.java:831)"
        ]
    }
}
```

**Comment by jelenadreskai** [comment]
@olliefreeman I've seen the same issue in the previous release. The user is part of the Container Administrator group.

If I add the same user to be in the group of users who are Editors (even though I think I should not be doing this at the Folder level), then the tree gets populated properly. However when I initiate the import, there are no folders shown in the drop down list for the importer to pick from.
