### ISSUE TITLE
Excel Importer: reference data type name changes ignored

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-core#220]
1. One version of data model is created, and contains a reference data type
2. Export data model
3. Update reference data type name from 'old_name' to 'old_name_ref'
4. Import a new version of the same data model

Current behavior:
Reference data type name change ignored completely. Tables properly associated, but name was not updated.

Expected results:
Reference data type names were updated.

Additional Notes:
Referenced data types by default get the same name as a table (view) when imported by the SQL Importer. We have a user who is trying to change the name of these data types using Excel importer, but importer is ignoring the updated data type name (for reference data types).

**Comment by olliefreeman** [comment]
think this belongs under the excel plugin repo.

**Comment by olliefreeman** [comment]
moved to https://github.com/MauroDataMapper-Plugins/mdm-plugin-excel/issues/6
