### ISSUE TITLE
Cannot move a sub folder up to the root

### ISSUE THREAD

**Issue by olliefreeman** [MauroDataMapper/mdm-core#235]
You cannot move a folder which is inside another folder out of all folders, 
the url would be `/api/folders/$folderId/folder/null` which is not allowed.

We need to code in the ability to move a folder into the "root"

**Comment by jamesrwelch** [comment]
At the moment this is achieved in the UI by `PUT /api/folders/$folderId` with `"parentFolder":null` in the body

**Comment by olliefreeman** [comment]
Updating controller to accept the `destination_folder_id` in the URL `http://localhost/api/folders/{{folder_id}}/folder/{{destination_folder_id}}` as the value `root`

If it is == `root` then the parent folder will be set to null and the folder will be moved to the root
