### ISSUE TITLE
Apply a business created profile to a Codeset

### ISSUE THREAD

**Issue by alanpnhs** [MauroDataMapper/mdm-core#238]
Please fill in the sections below, adding/removing information where applicable:

# Description

When attempting to apply a profile (in this case DD4C Profile (Standard)) to a Codeset, the system failed, presenting a failure message "There was a problem getting the selected profile".

# Steps to reproduce - please see attached error report which shows screen shots taken whilst producing the error.

[error report.docx](https://github.com/MauroDataMapper/mdm-ui/files/7950891/error.report.docx)

# Error details
```
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 404,
  "statusText": "OK",
  "url": "https://modelcatalogue.cs.ox.ac.uk/nhsd-test/api/codeSets/b84af776-c1e3-4736-ad64-c17601517ede/profile/uk.ac.ox.softeng.maurodatamapper.profile.provider/DD4C+Profile+%28Standard%29",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://modelcatalogue.cs.ox.ac.uk/nhsd-test/api/codeSets/b84af776-c1e3-4736-ad64-c17601517ede/profile/uk.ac.ox.softeng.maurodatamapper.profile.provider/DD4C+Profile+%28Standard%29: 404 OK",
  "error": {
    "path": "/api/codeSets/b84af776-c1e3-4736-ad64-c17601517ede/profile/uk.ac.ox.softeng.maurodatamapper.profile.provider/DD4C+Profile+(Standard)",
    "resource": "ProfileProviderService",
    "id": "uk.ac.ox.softeng.maurodatamapper.profile.provider:DD4C+Profile+(Standard)"
  }
}
```

**Comment by olliefreeman** [comment]
Theres currently an issue with how dynamic profile names are handled when being passed around in urls, basically special characters/punctuation other than the simple "space" will not work. So please keep your names restricted to using alphanumeric characters and spaces.

**Comment by olliefreeman** [comment]
8ff2aa6245ee90f4a8345f555c15f47dd84b0b71 fixes this
