### ISSUE TITLE
Data Class ordering not maintained when creating a new version

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#241]
When creating a new version of a model, the classes are copied but the ordering is not maintained.  This happened within a versioned folder, but I assume the issue applies on a single model as well.  The `idx` field in the database is set, but not with the correct ordering.

**Comment by olliefreeman** [comment]
This will need the idx field added to modelitems when copied, and then careful examination of the `uk.ac.ox.softeng.maurodatamapper.core.traits.domain.IndexedSiblingAware#fullSortOfChildren` method which is used when branching/validating new models
