### ISSUE TITLE
'Imported' data elements not persisted when creating new versions

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#242]
I have a VF which has a core model, with data elements in.  I have other models in the VF which re-use those elements by importing.  When I create a new version / branch, that re-use is not copied into the new model.  Similarly for data classes that 'extend' other data classes

**Comment by olliefreeman** [comment]
Imported and extended are currently not included in the "copy" method, this is due to them being added and not fully used so they weren't completed

**Comment by olliefreeman** [comment]
This will need to follow similar patterns to ModelDataTypes and Terms inside Codesets for branching and merging
