### ISSUE TITLE
Update semantic link and version link endpoints return previous instance

### ISSUE THREAD

**Issue by joe-crawford** [MauroDataMapper/mdm-core#258]
# Description

The endpoint to update a semantic link (PUT to `/api/{{domain_type}}/{{domain_id}}/semanticLinks/{{semantic_link_id}}`) updates the link successfully but returns the previous instance data in the response.

Also applies to the endpoint to update a version link (PUT to `/{{model_domain_type}}/{{model_id}}/versionLinks/{{version_link_id}}`).

# Steps to reproduce

1. Create a Semantic Link - in Postman POST to `/api/{domainType}/{domainId}/semanticLinks`:
```json
{
    "targetMultiFacetAwareItemDomainType": "{{target_domain_type}}",
    "targetMultiFacetAwareItemId": "{{target_domain_id}}",
    "domainType": "SemanticLink",
    "linkType": "Refines",
    "unconfirmed": {{$randomBoolean}}
}
```
2. Update the same link to a different targetMultiFacetAwareItemId using the PUT endpoint with same structure as above.
3. Previous targetMultiFacetAwareItemId is returned in response.

Similarly for version links.

# Expected behavior

Updated data should be returned on update.

# Screenshots

# Environment

Please complete the following information:
- mdm-core latest develop

**Comment by olliefreeman** [comment]
arguably one would not actually be updating a SL to point to a different target, they would instead delete the existing SL and create a new one. howver the code should still work and handle this
