### ISSUE TITLE
Data Model subset endpoint does not maintain Data Class hierarchy in target model

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#269]
Please fill in the sections below, adding/removing information where applicable:

# Description

Found an instance where subsetting a Data Model which included a DC parent/child hierarchy did not recreate that hierarchy in the target model.

# Steps to reproduce

The following steps are taken from the "Complex Test DataModel" from the development database.

Create a HTTP request as follows:

```http
PUT /api/dataModels/{sourceId}/subset/{targetId}

{
  "additions": [ ...DE uuids... ],
  "deletions": []
}
```

The `sourceId` should be the UUID for "Complex Test DataModel", the `targetId` should be a new empty Data Model you create.

For the Data Element UUIDs, select these elements:

![image](https://user-images.githubusercontent.com/3219480/154479112-f63cf73b-d3d3-44ef-add9-a7f80212f289.png)

![image](https://user-images.githubusercontent.com/3219480/154479151-6f3f1fdc-1abb-4f59-9670-9f508a293fd6.png)

Note that "child" DE uses a reference DT linked to the "child" DC. This is correctly copied too, but will produce this target hierarchy:

![image](https://user-images.githubusercontent.com/3219480/154479531-67df302b-aa5b-40e6-bc33-d068a6a13785.png)

# Expected behavior

I would have expected the target model to also have the same DC hierarchy:

```
* Data Model
  * parent
    * child
  * content
```

# Environment

Please complete the following information:
- mdm-core Version 5.1.0-SNAPSHOT

**Comment by aaronforshaw** [comment]
I think this is not directly related to the subsetting, but to the copying of reference types. Other scenarios which do not work are:
- Create a new Data Model and try to add a Data Type by copying 'child' from the Complex Test DataModel. DataTypeController throws an exception 'Copying of ReferenceType DataTypes is not possible'
- Create a new Data Model. Add an empty Data Class. Try to add a Data Element to this empty Data Class by copying the 'child' Data Element from Complex Text DataModel. DataClassService throws an exception "errorCode": "DCS01",
    "message": "Cannot find DataClass for path [parent|child] as DataClass [parent] does not exist"

**Comment by aaronforshaw** [comment]
At https://github.com/MauroDataMapper/mdm-core/blob/d6818d98e5868d22597e1a205ea661fb4f1b3e47/mdm-plugin-datamodel/grails-app/services/uk/ac/ox/softeng/maurodatamapper/datamodel/item/DataClassService.groovy#L604 need to use ```targetDataClass = copyCatalogueItemInformation(sourceDataClass, targetDataClass, user, userSecurityPolicyManager)``` rather than copying the label, description and createdBy properties. However, doing so causes an exception in semantic link when saving
