### ISSUE TITLE
Getting child items under a folder does not order them alphabetically

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#271]
Please fill in the sections below, adding/removing information where applicable:

# Description

When using the `GET /api/tree/folders/{id}` endpoint, the response does not order the child items below that folder in alphabetical order.

# Steps to reproduce

Using the "Development Folder" in a dev instance, call the above endpoint where the `{id}` is the ID of "Development Folder". Then note the response returned.

# Expected behavior

All items returned should be in alphabetical order.

# Screenshots

This is an example from the UI when expanding the tree, found during review of MauroDataMapper/mdm-ui#469:

![image](https://user-images.githubusercontent.com/3219480/154931333-977abb68-3425-4fda-b867-5c50d56b05b2.png)

# Environment

Please complete the following information:
- mdm-core Version 5.1.0-SNAPSHOT

**Comment by olliefreeman** [comment]
so looking at this screenshot...i seem to recall that models follow the same rules as DCs inside a DM for a tree.
they should be grouped by those with and without children, however inside those groups they should absoluetely be organised alphabetically...we had long discussions about this when we designed the tree response for MDC.

I think now that things have moved on a bit, then there should be some further discussion about ordering.

@pjmonks @jamesrwelch @joe-crawford thoughts based on the following:

* Needs to look good. We decided with previous discussion that mixing + and no + looks messy
* Current sort order **should** be 
  * Folders alphabetical
  * Models are those with children first, then those without and inside those 2 groups are alphabetical
  * DCs are same as models
  * Terms are same as models
  * For a folder with both folders and models, it should be folders first, then models following model sorting rules
* We now have multiple models with branch names, currently unsorted
  * Versions first, then branches or branches first then versions (sorted by version/alphabetically) inside those 2 groups
* For a folder with multiple types of models i feel models should be grouped, so DMs then Ts then CSs the RDMs

**Comment by pjmonks** [comment]
From the perspective of a UI, you've raised a point where a folder containing sub-folders and models could be ordered:

1. Sub-folders in label order (ascending)
2. Then models in label order (ascending)

This has precedence, since file explorers in Mac/Windows/Linux follow this pattern too. It may become a bit more complex once branches and finalised versions are added to the list too.

Nonetheless, I imagine a user viewing this through a visual interface like `mdm-ui` would expect an alphabetical listing - the separation of sub-folders vs models sounds reasonable.

Or are there query parameters that could be added to the endpoint to control the sort order, e.g. `sort=label`?

**Comment by olliefreeman** [comment]
i think the tree order should be controlled by us without params, as you say its a familiar concept with file explorer, and i do agree that it should be folders then models.

**Comment by jamesrwelch** [comment]
Yep, I'm happy for this to be a back-end thing for the time being.  We may have times where we want the UI to override the default ordering, but not now.

**Comment by jamesrwelch** [comment]
And I agree with sub-folders in label ordering, then DMs in label order.

**Comment by jamesrwelch** [comment]
I'm not sure about differentiating models with children vs models without

**Comment by olliefreeman** [comment]
Just for absolute confirmation
ContainerTreeItem
```groovy
@Override
    int compareTo(TreeItem that) {
        def res = this.domainTypeIndex <=> that.domainTypeIndex
        if (res == 0) res = this.label <=> that.label
        res
    }
```
Model TreeItems
```groovy
  @Override
    int compareTo(TreeItem that) {
        def res = super.compareTo(that)
        if (that instanceof ModelTreeItem) {
            if (res == 0) res = this.documentationVersion <=> that.documentationVersion
            if (res == 0) res = this.modelVersion <=> that.modelVersion
            if (res == 0) res = this.branchName <=> that.branchName
        }
        res
    }
```
ModelItem TreeItems
```groovy
 @Override
    int compareTo(TreeItem that) {
        def res = this.domainTypeIndex <=> that.domainTypeIndex
        if (res != 0) return res

        ModelItemTreeItem other = that as ModelItemTreeItem
        res = this.hasChildren() <=> other.hasChildren()
        if (res == 0) res = this.order <=> other.order
        if (res == 0) res = this.label <=> other.label
        res
    }
```

**Comment by olliefreeman** [comment]
The domainTypeIndex controls what order the domains come in, so Folders, then Models, do we want to group models of the same type or just allow global model label ordering??

**Comment by jamesrwelch** [comment]
Containers: whether you want Folders first, then models, or all mixed in together, I guess depends whether you're a Windows / Mac user.  I don't mind that much, I think.  Listing models by name, then version, then branch is fine.
Within a model, I think there are two options: if the items have an ordering, they should be presented in that order.  If there is no ordering set, they should be in alphabetical order.  I'm not sure whether they have child classes or not should factor in... in the past it's been helpful to view complex XSDs, but the more general use cases probably override that

**Comment by olliefreeman** [comment]
i def think we want folders first, then models, but its more about then when we list the models do we jumble terminologies, CSs, DMs and RDMs all up together sorted by label, or collect each model type and then sort by label inside that collection?

Id rather not push idx values up to the treeitem, i feel that the tree should display sorted by label always, then the "list" page should sort by idx,label

**Comment by jamesrwelch** [comment]
I think mixing all model types is fine.  Any other ordering would be arbitrary - if people want to separate their model types they can create sub-folders.
I think ordering of classes might be important enough to appear in the tree... if you're modeling a form, or even an XSD, then it would look odd / confusing to see your classes in any other order.  But for some models - DBs, UML, etc, ordering is not important

**Comment by olliefreeman** [comment]
![Screenshot 2022-02-22 at 17 19 26](https://user-images.githubusercontent.com/2587424/155184449-07166b77-8341-4867-a1f4-7e6e557b26ad.png)
![Screenshot 2022-02-22 at 17 19 43](https://user-images.githubusercontent.com/2587424/155184469-dd41b5a8-e237-450d-ad3b-24b17220be8d.png)
![Screenshot 2022-02-22 at 17 19 54](https://user-images.githubusercontent.com/2587424/155184470-2997c34c-e610-4747-8e9d-c5f401c67eb7.png)

**Comment by olliefreeman** [comment]
@pjmonks @jamesrwelch happy with the above sorting???

**Comment by olliefreeman** [comment]
![Screenshot 2022-02-22 at 17 21 09](https://user-images.githubusercontent.com/2587424/155184684-5ef1d9c1-64f7-4d39-8c50-89b36174965a.png)

**Comment by olliefreeman** [comment]
i'd missed 1 `.sort()` call in the entire service, basically stopped sorting the drill down trees, just want to make sure we dont want to change the actual built in sorting before i commit this
