### ISSUE TITLE
Permissions error on delete unused data classes and unused data types endpoints on data model

### ISSUE THREAD

**Issue by joe-crawford** [MauroDataMapper/mdm-core#272]
# Description

The `PUT /dataModels/{{data_model_id}}/dataClasses/clean` and `{{base_url}}/dataModels/{{data_model_id}}/dataTypes/clean` endpoints give a 403 Forbidden error when called.

# Steps to reproduce

1. Logged in as an admin user, create a new data model with default data types containing only an empty data class.
2. Call the `PUT /dataModels/{{data_model_id}}/dataClasses/clean` and `{{base_url}}/dataModels/{{data_model_id}}/dataTypes/clean` as the admin user.
3. A 403 error is returned, e.g.:
```json
{
    "path": "/api/dataModels/0244b8d9-b3e3-49c2-81a4-63c0bd5149c2/dataClasses/clean",
    "additional": "User does not have the necessary permissions"
}
```

# Expected behavior

Unused data types or data classes should be deleted from the data model when called by a user with appropriate permissions.

# Environment

- mdm-core latest develop 

# Additional context

When logged in as admin user, access to the endpoints is prevented at TieredAccessSecurableResourceInterceptor.groovy, line 81.

**Comment by joe-crawford** [comment]
Comment from @olliefreeman: URL mappings for these endpoints could probably be removed.

**Comment by olliefreeman** [comment]
basically we added these for MDC for james and I to use to clean up some DMs, they were never intended for public consumption and we never really used them. So yes, lets delete the endpoints and the controller methods
