### ISSUE TITLE
Allow filtering superseded versioned folders in tree

### ISSUE THREAD

**Issue by joe-crawford** [MauroDataMapper/mdm-core#288]
# Description

The tree endpoints include parameters for filtering models to only latest versions (`includeModelSuperseded` and `includeDocumentSuperseded`). Versioned Folders should also be allowed to be filtered in the tree using these parameters.

# Additional context

From discussion: `includeModelSuperseded` should be used for both models and versioned folders. 

Related to: maurodatamapper/mdm-ui#490, adding these params would allow the UI option to apply to versioned folders as well.

**Comment by olliefreeman** [comment]
At the same time we want to add an ApiProperty that is bootstrapped in mdm-core/mdm-core to value `false` which allows admin users to set the default for "includeModelSuperseded" which should be loaded inside TreeItemController and that value passed to the service if the query param is not supplied
