### ISSUE TITLE
Path errors on CSV Reference Data Model import

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#302]
When importing a Reference Data Model from CSV, an error (`Property [path] cannot be null`) is thrown for every row.  See attached for an example CSV file which should import

[CHP names and codes SC as at 04_12.csv](https://github.com/MauroDataMapper/mdm-core/files/8483997/CHP.names.and.codes.SC.as.at.04_12.csv)

**Comment by jamesrwelch** [comment]
Another example
[Westminster Parliamentary Constituency names and codes UK as at 12_14.csv](https://github.com/MauroDataMapper/mdm-core/files/8484009/Westminster.Parliamentary.Constituency.names.and.codes.UK.as.at.12_14.csv)

**Comment by olliefreeman** [comment]
the csv importer wasnt setting the model name, this is now being fixed
