### ISSUE TITLE
API endpoint to get the latest finalised data model by data model label

### ISSUE THREAD

**Issue by GBishop-PHSA** [MauroDataMapper/mdm-core#363]
# Description

The API currently provides a Get request to return the latest data model using the data model path (label and optional version number). When the version number is excluded from the path, it returns draft models, if one exists for that label. An additional request parameter to limit results to the latest finalised data model would be helpful for sharing links to published data models through email or internal documents.

# Additional context

Current API request to find latest data model by label: 
http://localhost:4200/#/catalogue/dataModel/dm:PATH
* where PATH can also include a specific version number,  dm:SampleModel$1.0.0

New request parameter for API request to find latest finalised data model by label:
http://localhost:4200/#/catalogue/dataModel/dm:PATH?finalised=true
* where PATH does not include a version number,  dm:SampleModel?finalised=true

**Comment by GBishop-PHSA** [comment]
Ready for review
mdm-ui PR: https://github.com/MauroDataMapper/mdm-ui/pull/665
mdm-core PR: https://github.com/MauroDataMapper/mdm-core/pull/364

**Comment by joe-crawford** [comment]
Closing as completed.
