### ISSUE TITLE
Save Theme images in the database

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-core#394]
# Description

The Mdm Explorer is being updated to allow admin users to change colours, fonts and logos of the Mdm Explorer. The management of the themes will me handled in the Mdm UI using Api Properties. We also need to give the admin user the ability to upload an image that can be used as a logo. This image needs to be saved in the backend. This task is to carry out the backend changes required to support this.

# Additional context

We already have a database table to hold image files called `user_image_file`. At the moment this is closely tied to users. This needs to be made more generic to handle images associated with other types of data. 
1. Rename the `user_image_file` table to be `image_file`. (Rename all references in the code to make sure this stays as is)
2. Change the column `user_id` so that it is nullable. 
A script in `mdm-core/grails-app/conf/db/migration/core/` will be required to do this.

In `mdm-core/grails-app/controllers/uk/ac/ox/softeng/maurodatamapper/core/file` create two new files called `ThemeImageFileController.groovy` and `ThemeImageFileInterceptor.groovy`. These should be based on the existing `UserImageFileController.groovy` and `UserImageFileInterceptor.groovy` files. 

`ThemeImageFileController.groovy`: This needs to keep all the same methods as were copied from `UserImageFileController`, but the contents of those methods need to use an api key to identify the image that is being shown or updated or saved. This should be done by calling a new service called `ThemeImageFileService`, that will handle the processing. `ThemeImageFileService `should be based on `mdm-core/grails-app/services/uk/ac/ox/softeng/maurodatamapper/core/file/UserImageFileService.groovy` and live in the same folder. This needs to be able to handle any api property name, where the value of the api property is the Id of the image file that has been uploaded. For the logo, the new api property key will be called `theme-image-header-logo`.

`ThemeImageFileInterceptor.groovy`: This needs to only allow admin users. (Talk to Joe Crawford for more info)

**Comment by joe-crawford** [comment]
Thanks @NigelPalmer.

For the `image_file` table there should be an `ImageFile` domain object, which should have all the image related fields and the ThemeImageFile and UserImageFile domain objects can inherit from this. Similar to how VersionedFolder inherited from Folder and both use the same `folder` table. Also similar to `DataType` and `SubscribedCatalogueAuthenticationCredentials` and subclasses.

It may be there aren't enough methods to need two service classes so you could have just one `ImageFileService` that has methods for both.
