### ISSUE TITLE
Migration error when starting backend with a fresh database

### ISSUE THREAD

**Issue by abwilson23** [MauroDataMapper/mdm-core#411]
A table change in a migration in the core project is causing an error in a migration applied later which is contained in the security project. 
The error can be reproduced by:

1. Dropping the maurodatamapper database
2. Creating a new one
3. Running `gradle bootrun` in mdm-testing-functional. 

The message should be:

![image](https://user-images.githubusercontent.com/6440992/232539033-f16ed2b9-3c07-4cb4-9bd9-aab93676bca4.png)

**Comment by joe-crawford** [comment]
Closed by PR 412.
