### ISSUE TITLE
Allow annotations to persist to a new version of a Data Model

### ISSUE THREAD

**Issue by GBishop-PHSA** [MauroDataMapper/mdm-core#415]
# Description
When creating a new draft data model from a previous version, the annotations (comments and attachments) are not copied to the new draft version.  

This feature could enabled/disabled through a new configuration property
Key: feature.copy_annotations_to_new_version    
Category: Features
Value: true

# Additional context
- the CatalogueItemService will check the config property and if true, copy all annotations(comments) and referenceFiles(attachements) to the new version

**Comment by GBishop-PHSA** [comment]
Pull requests for this ticket
https://github.com/MauroDataMapper/mdm-ui/pull/816
https://github.com/MauroDataMapper/mdm-core/pull/425

**Comment by joe-crawford** [comment]
Closing as resolved by #425.
