### ISSUE TITLE
Add a filter in Search to hide superseded models

### ISSUE THREAD

**Issue by GBishop-PHSA** [MauroDataMapper/mdm-core#416]
# Description

Users of the Search page want to see search results of only the most recent versions of data models. A new filter option could be added to allow users to select whether they will see superseded versions or not, in the search results.

# Additional context

The search controller could be updated to accepts an additional parameter indicating whether superseded versions should appear in the search results. The UI would show this option on the Advanced Search as well as the Search Filter section of the search results page.

![SearchScreenShowSupercededFilter](https://github.com/MauroDataMapper/mdm-core/assets/90805521/8f793976-fa65-4e82-91df-15982527a8d4)
![SearchScreenShowSuperceded](https://github.com/MauroDataMapper/mdm-core/assets/90805521/451faaf5-7b1a-4bf3-9f46-6b8ac668cb2a)

**Comment by GBishop-PHSA** [comment]
Pull requests for mdm-core and mdm-ui
https://github.com/MauroDataMapper/mdm-ui/pull/815
https://github.com/MauroDataMapper/mdm-core/pull/424

**Comment by jamesrwelch** [comment]
@GBishop-PHSA Thank you so much for these PRs!  We'll review them in the next day for two :)

**Comment by GBishop-PHSA** [comment]
@joe-crawford Thank you for making the changes to the pull requests. If they're both merged, can this ticket be closed?

**Comment by joe-crawford** [comment]
Yes, sorry for the delay, closing as resolved by #424!
