### ISSUE TITLE
Crash attempting to merge a finalised model - version folder

### ISSUE THREAD

**Issue by OButlerOcc** [MauroDataMapper/mdm-core#463]
Versioned folders allow you to merge a finalised branch which causes a comparison error

Create the following:
![image](https://github.com/MauroDataMapper/mdm-core/assets/85611988/5224ff81-6f7a-4e7b-ab5e-ebffce59420f)

1. one tagged finalised branch, 
2. one non finalised main branch
3. one other branch.

5. go to merge on the testbranch

![image](https://github.com/MauroDataMapper/mdm-core/assets/85611988/2f4f0de9-f270-4525-9d45-cde3b80d6711)

6. select the finalised branch that appears in the merge screen.

![image](https://github.com/MauroDataMapper/mdm-core/assets/85611988/f563360b-fa07-4867-8ab2-486d784e0703)

7. note the crash and error that occurs during the merge diff calculation.

**Comment by jamesrwelch** [comment]
@OButlerOcc Do you have a stack trace?

**Comment by pjmonks** [comment]
Isn't the issue more that the list of available branches to merge into includes finalised versioned folders? 

The branch selector component in the UI is calling the `GET /api/versionedFolders/{id}/simpleModelVersionTree?branchesOnly=true`. For data models this returns just the draft branches, perhaps there is an issue with the `versionedFolder` domain endpoint - maybe the `branchesOnly` parameter is ignored? Something to look into.

**Comment by jamesrwelch** [comment]
Is it related to this failing test in Jenkins?  https://jenkins.cs.ox.ac.uk/job/Mauro%20Data%20Mapper/job/mdm-core/job/develop/513/testReport/junit/uk.ac.ox.softeng.maurodatamapper.datamodel/DataModelFunctionalSpec/Functional_Tests___Functional_Test__mdm_plugin_datamodel___MI07___test_merging_diff_into_draft_model_using_new_style/
