### ISSUE TITLE
DataModel - Main Branch is empty

### ISSUE THREAD

**Issue by Ansh1980** [MauroDataMapper/mdm-core#62]
This error is occurring  only on certain DataModels which is finalised & Branch  is empty. Screenshot attached shows branch should be "main". Right now because of the error it redirects to Server Error Page.

```
devMode: true
errorCode: "UEX--"
exception: {type: "IllegalArgumentException",…}
message: "No enum constant uk.ac.ox.softeng.maurodatamapper.core.facet.VersionLinkType.SUPERSEDED_BY_MODEL"
path: "/api/dataModels/0b308f71-52e8-4fe3-929d-51efbc5e4048/modelVersionTree"
reason: "Internal Server Error"
status: 500
version: "4.4.0-SNAPSHOT"
```
<img width="368" alt="Screenshot 2021-04-21 at 11 34 44" src="https://user-images.githubusercontent.com/40128949/115540182-bd054c80-a295-11eb-9187-a210a71fa772.png">

**Comment by olliefreeman** [comment]
closing as suspected bug from a bad-state ui
