### ISSUE TITLE
Group Access Public Readable causes new group to be created

### ISSUE THREAD

**Issue by gammonpeter** [MauroDataMapper/mdm-core#64]
**Describe the bug**![image](https://user-images.githubusercontent.com/53000624/116379215-b3866200-a80a-11eb-875e-73713e570674.png)Upon calling http://localhost:8080/api/dataModels/fa541d3b-28a1-42bf-a0f5-3642567b7928/readByEveryone, a new group is created when it shouldn't

**To Reproduce**
Go to a DM click user groups and click publicly  readable, reload group access notice theres a new group

**Expected behavior**
Updated but no new group

**Screenshots**
![image](https://user-images.githubusercontent.com/53000624/116379215-b3866200-a80a-11eb-875e-73713e570674.png)**Desktop (please complete the following information):**

**Comment by olliefreeman** [comment]
So there should actually be at least 1 group in the list as if you create a Model a group is auto generated for your user to own that model. The "bootstrapped" models fall into a hole where they completely inherit access from the folder.

However there should not be an additional securableResourceGroupRoles each time you hit the endpoint
