### ISSUE TITLE
Branched model does not show Summary Metadata

### ISSUE THREAD

**Issue by theresanoble** [MauroDataMapper/mdm-core#70]
**Describe the bug**
In a branched model, the summary metadata is not visible, despite it being visible in the finalised version.

**To Reproduce**
Steps to reproduce the behaviour:
1.  I was using the CDW instance
2.  Open COVID-19 Data Product Database both the finalised and documentation versions
3. open any of the data elements (same one in both models) -- I was looking at data_criteria_biochemistry - click on data tab
4. In finalised you can see the summary metadata, in documentation it is empty, in finalised it is still visible.
visable**Expected behaviour**

I would expect there to be the same summary metadata viewable in both finalised and branched versions of the model

![Screenshot 2021-05-13 at 09 29 45](https://user-images.githubusercontent.com/67739552/118100269-2c221c80-b3ce-11eb-884f-ed0e9bf12a57.png)
<img width="1680" alt="Screenshot 2021-05-13 at 09 32 48 2" src="https://user-images.githubusercontent.com/67739552/118100308-36dcb180-b3ce-11eb-8fce-41f4f70eecb0.png">

**Desktop (please complete the following information):**
 - OS: Mac 11.3.1
 - Browser safari
 - Version 14.1

**Comment by aaronforshaw** [comment]
I started with a finalised model having summary metadata and am able to reproduce the issue described by @theresanoble. 

From the UI, there are three ways to copy a Data Model:
1. New Fork: In this case, the backend explicitly sets a flag to not copy summary metadata to the new fork
2. New Version: the backend copies summary metadata at the Data Model level, but not for the Data Class or Data Elements
3. New Branch: ditto (2)

@olliefreeman I assume that in (2) and (3) summary metadata should be copied for the Data Class and Data Elements, but please confirm if the behaviour in (1) for New Fork is correct.

**Comment by olliefreeman** [comment]
@aaronforshaw yup, fork should never copy SM, but branching and new versions (model and documentation) should.
