### ISSUE TITLE
Bootstrap a single folder to improve experience on fresh install

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#74]
When you first install an instance of Mauro, you cannot create or import any models until you've created a folder.  It would make sense for a fresh install to include a single, default folder to reduce the number of steps between installing and having usable models.

**Comment by olliefreeman** [comment]
change of mind after seeing it in mdm-application-build .... it doesnt belong there ...
* we should bootstrap the folder in the mdm-core/**/Bootstrap with a simple description
* we should update the folder in mdm-security/**/Bootstrap 
   * adding the "access information"
   * adding the administrator group access
