### ISSUE TITLE
Inconsistent trimming during Terminology import

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-core#77]
The terminology below has a term code with a space in it (`A `).  When the terms are imported, the code is trimmed, which means that when the relationship is created, it get a null pointer exception.  Is there anything we can do to stop this?  It's a minor issue, but took me a long while to find with a much larger terminology.

```json
{
    "terminology": {
        "label": "Test Terminology (Trimming)",
        "author": "James Welch",
        "organisation": "Oxford BRC ",
        "documentationVersion": "1.0.0",
        "finalised": false,
        "termRelationshipTypes": [
            {
                "label": "narrowerThan",
                "displayLabel": "Narrower Than",
                "parentalRelationship": false,
                "childRelationship": true
            }
        ],
        "terms": [
            {
                "code": "A ",
                "definition": "Alpha",
                "depth": 1
            },
            {
                "code": "B",
                "definition": "Beta",
                "depth": 2
            }
        ],
        "termRelationships": [
            {
                "relationshipType": "narrowerThan",
                "sourceTerm": "B",
                "targetTerm": "A "
            }
        ]
    }
}
```

**Comment by jamesrwelch** [comment]
JSON Terminology importer

**Comment by olliefreeman** [comment]
theres no trimming actively happening..so this is odd

**Comment by olliefreeman** [comment]
Please create a test class `JsonTerminologyImporterImporterServiceSpec` which you can use the `JsonTerminologyImporterExporterServiceSpec` to properly add import tests for the files we test exporting, and add a new file for import testing using the attached JSON

**Comment by olliefreeman** [comment]
grails automatically trims when it databinds
