### ISSUE TITLE
Cached folder tree request returns 500 response

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#82]
**Describe the bug**
When requesting the folder tree using `/api/tree/folders`, this will return a `500` error. Only if the `noCache` query parameter is supplied will a `200` response come back.

This was first noticed after pulling down latest changes after versioned folder support was added to the tree.

**To Reproduce**
Send this request, which is the same as what the UI does on the first load of the model tree:

```http
/api/tree/folders?includeDocumentSuperseded=false&includeModelSuperseded=true&includeDeleted=false
```

This will fail. For comparison, you can also send this request which will succeed, this is the same as the model tree forcing a refresh via the UI's refresh button:

```http
/api/tree/folders?includeDocumentSuperseded=false&includeModelSuperseded=true&includeDeleted=false&noCache=true
```

**Expected behavior**
Both requests should return a `200` response with the required folder tree contents.

**Additional context**
The log file produced by the backend is attached for reference:

[mdm-testing-functional.log](https://github.com/MauroDataMapper/mdm-core/files/6615209/mdm-testing-functional.log)

**Comment by olliefreeman** [comment]
Obviously we want to handle it if the parameter is not even in the url but what happens if you try with noCache=false ???

**Comment by pjmonks** [comment]
@olliefreeman Just tried `noCache=false` and it makes no difference, still returns a `500` response.

**Comment by pjmonks** [comment]
As a final attempt to remove this issue I was having, I created a new bootstrapped database from `mdm-testing-functional` and now I don't have these tree loading issues anymore. 

I would be interested to know what cached data was causing the issue originally, especially if this means other users have issues with their own upgraded instances, but the immediate problem seems resolved for me now.

**Comment by olliefreeman** [comment]
we were struggling to replicate it...however thanks to the stacktrace i can work on how to actually make sure it cant happen
