### ISSUE TITLE
Folder tree endpoint can incorrectly return "createVersionedFolder" action

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#83]
**Describe the bug**
It is possible for the `createVersionedFolder` allowed action to be returned in the `/api/tree/folders` response in some cases when it should not be allowed.

**To Reproduce**

1. Create a new Versioned Folder called "Versioned Folder Test". This can be at the root of the tree or within an existing folder, but it must be the first ancestor of its type.
2. After that, create a new Folder called "Folder Test" where "Versioned Folder Test" is the parent.
3. Call `/api/tree/folders` after this hierarchy is created and note the `availableActions` field of "Folder Test". When testing in the UI, it includes the `createVersionedFolder` action.

**Expected behavior**
This scenario should not be allowed because no further Versioned Folders should be created under another Versioned Folder, even if the Versioned Folder parent is an indirect ancestor.

**Comment by olliefreeman** [comment]
what do we think is the likelihood that a user would move a folder from inside a VF into another VF????
