### ISSUE TITLE
Cannot import a model into a Versioned Folder

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-core#89]
**Describe the bug**

When trying to import a model into a draft Versioned Folder, the import fails returning a `500 Internal Server Error`.

**To Reproduce**

Using the UI:

1. Create a draft Versioned Folder called "Test Versioned Folder".
2. Now from the UI select the "Import > Import Data Models" option.
3. Select any suitable importer (JSON for using the sample below).
4. Select the source file (see below).
5. Under "Folder Location" select the "Test Versioned Folder".
6. Pick a new name for the model that will be created.
7. Click "Import Model(s)"

**Expected behavior**

The model should have been imported into the Versioned Folder and the UI should refresh to show the newly created model under the Versioned Folder.

**Screenshots**

![image](https://user-images.githubusercontent.com/3219480/122430395-7a0ce000-cf8b-11eb-81c4-9891140e9ae8.png)

**Additional context**

Sample JSON file to import: 
[complex_test_datamodel_20210617T144040.zip](https://github.com/MauroDataMapper/mdm-core/files/6671503/complex_test_datamodel_20210617T144040.zip)

`mdm-core` log file produced: 
[mdm-testing-functional.log](https://github.com/MauroDataMapper/mdm-core/files/6671506/mdm-testing-functional.log)

**Comment by pjmonks** [comment]
Re-opening this issue as it doesn't seem solved, at least when running from the UI.

**Comment by olliefreeman** [comment]
definitely fixed this time, tests included to prove it
