### ISSUE TITLE
Subscribing to a model on the same catalogue gives error 

### ISSUE THREAD

**Issue by oughnic** [MauroDataMapper/mdm-core#91]
Subscribing to a model on the same catalogue gives error 
```
Property [subscribedModelType] of class [uk.ac.ox.softeng.maurodatamapper.federation.SubscribedModel] cannot be null 
```

**To Reproduce**
Create and API key on an instance
Use the API key to subscribe to the catalogue (subscribe to its own endpoint)
Subscribe to a model

**Expected behavior**
The subscribed model is expected to be
**Screenshots**
![Mauro-error](https://user-images.githubusercontent.com/27196895/122764319-45549d80-d297-11eb-82cd-71a6aa1a3c1f.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [91.0.864.54]

**Comment by olliefreeman** [comment]
also you shouldn't be able to subscribe to a model from the same catalogue as there will be a failure on the label and authority being the same...so there seem to be 2 issues here...
1. Whats causing the validation error Nicholas has sent
2. Why isn't there also a validation error relating to the authority and label

**Comment by olliefreeman** [comment]
UI sends
```
POST /api/subscribedCatalogues/{catalogueId}/subscribedModels
```
```json
{
    "subscribedModelId": {modelIdToFederate},
    "folderId": {targetLocalFolderId}
}
```

**Comment by olliefreeman** [comment]
so the workflow actually expects the API to "federate" the subscribed model when its created, this currently doesn't happen, it expects a separate call to perform the federation. 
Thie expectation actually doesn't make sense...the API should federate the model when its subscribed.
