### ISSUE TITLE
Merge error

### ISSUE THREAD

**Issue by oughnic** [MauroDataMapper/mdm-core#93]
**Describe the bug**
Error attempting to merge a simple model branch back to the main

**To Reproduce**
Mauro UI 6.2.0
Navigate to a branch, select Merge -> Merge Model
```
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 400,
  "statusText": "OK",
  "url": "https://mauro.oughtibridge.com/api/tree/dataModels/4e6d07b2-5b13-49e9-9ae7-241e451f4fbe?forDiff=true",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://mauro.oughtibridge.com/api/tree/dataModels/4e6d07b2-5b13-49e9-9ae7-241e451f4fbe?forDiff=true: 400 OK",
  "error": {
    "status": 400,
    "reason": "Bad Request",
    "errorCode": "TIS01",
    "message": "Container retrieval for container [DataModel] with no supporting service",
    "path": "/api/tree/dataModels/4e6d07b2-5b13-49e9-9ae7-241e451f4fbe",
    "devMode": false,
    "version": "4.6.0"
  }
}
```
**Expected behavior**
next screen to display as designed.

**Screenshots**
![image](https://user-images.githubusercontent.com/27196895/123413027-2e20f300-d5aa-11eb-9137-4472f016f7ab.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Browser [Edge]

**Comment by olliefreeman** [comment]
this is actually a UI issue in that they're using the wrong endpoint.
already raised in MauroDataMapper/mdm-ui/issues/200
