### ISSUE TITLE
UI: MetaData is not rendering under the 'other properties tag'

### ISSUE THREAD

**Issue by OButlerOcc** [MauroDataMapper/mdm-core#96]
The server is returning a 200 response with content but it is not rendering. See screenshot

![image](https://user-images.githubusercontent.com/85611988/123410938-cbc6f300-d5a7-11eb-83da-e0c4598f499b.png)

![image](https://user-images.githubusercontent.com/85611988/123411074-f31dc000-d5a7-11eb-8daf-69c6128cc088.png)

Json response from ss:
[response.json.txt](https://github.com/MauroDataMapper/mdm-ui/files/6715459/response.json.txt)

1. Steps to reproduce:
2. Use branch https://github.com/MauroDataMapper/mdm-core/tree/feature/mc-9540 as the backend. This will create the same data as above.
3. Drop and recreate the MauroDataMapper database.
4. Run the backend with grails run-app under the testing-functional profile
5. Open the UI
6. Login with Admin User
7. Open Model Version Tree Datamodel | 2.0.0 (see screenshot)
8. Change Default profile in dropdown to 'other properties'
9. Note no properties shown.

Edit Note: screenshot was scrolled halfway along. replaced it

**Comment by olliefreeman** [comment]
i was very confused as i know the MD index endpoint works, however this is not the endpoint the UI is using, its calling the otherMetadata endpoint from the profiles plugin. the code is not pushing the view in correctly which is why the MD isnt rendering

**Comment by olliefreeman** [comment]
this is not actually a bug, running on the develop branch. this is because @OButlerOcc's branch is way behind the develop branch and is missing important updated from @jamesrwelch. mc-9540 needs to be rebased onto the head of develop.
