### ISSUE TITLE
Merging newly imported models with existing  documentation 

### ISSUE THREAD

**Issue by theresanoble** [MauroDataMapper/mdm-core#99]
**Describe the bug**
Upon importing a new model with the SQL importer/scraping tool any existing documentation branches are not automatically merged with the new model, in addition when using the 'manual' merge tool within MDM it fails and you recieve this error:

{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 400,
  "statusText": "OK",
  "url": "https://oxnetdwa02.oxnet.nhs.uk/mauro-data-mapper/api/tree/dataModels/15a6af30-7f8f-484e-92f5-8e7c86898d23?forDiff=true",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://oxnetdwa02.oxnet.nhs.uk/mauro-data-mapper/api/tree/dataModels/15a6af30-7f8f-484e-92f5-8e7c86898d23?forDiff=true: 400 OK",
  "error": {
    "status": 400,
    "reason": "Bad Request",
    "errorCode": "TIS01",
    "message": "Container retrieval for container [DataModel] with no supporting service",
    "path": "/api/tree/dataModels/15a6af30-7f8f-484e-92f5-8e7c86898d23",
    "devMode": false,
    "version": "4.6.0"
  }
}

Also not able to import model that isn't already finalized
**To Reproduce**
1. Go to : https://oxnetdwa02.oxnet.nhs.uk/mauro-data-mapper/#/home
2. click on a model
3. click on 3 dots
4. click on merge

**Expected behavior**
Upon import the new model should automatically merge any existing documentation branch, and/or when selecting the merge function in MDM it should ... merge.

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser : Chrome 
 - Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context**

**Comment by olliefreeman** [comment]
this has already been raised in the UI

**Comment by olliefreeman** [comment]
MauroDataMapper/mdm-ui#200
